version: "3.9"
services:
   postgres: 
      image: postgres:latest
      ports:     
         - 5455:5432
      volumes:
        - /db:/var/lib/postgresql/data
      environment:
           POSTGRES_USER: auth-dvix-dev
           POSTGRES_PASSWORD: dvix-dev-psw
volumes:
    db:
      driver: local  
      


